name: dart_aoc
description: Advent Of Code solutions in Dart.
version: 1.0.0
homepage: https://www.github.com/ramanverma2k/AOC

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lint: ^2.0.1
  test: ^1.16.0
